//POST http://localhost:5000/api/auth/register

# POST http://localhost:5000/api/auth/login
# Content-Type: application/json

# {
#     //"name": "Harman Kaur",
#     "email": "harman1234@gmail.com",
#     "password": "1234@567"
# }


//GET http://localhost:5000/api/auth/me
# GET http://localhost:5000/api/books/search?q=the alchemist
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNGM4MWJhMWY3MDYwYTJlZjcxZWVhMiIsImlhdCI6MTc4MzU3NTM4MCwiZXhwIjoxNzg0MTgwMTgwfQ.smPBFh89tR2vb1PCU9aGhZHhyhKBqrab3bACUSL5lEw

# POST http://localhost:5000/api/books
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNGM4MWJhMWY3MDYwYTJlZjcxZWVhMiIsImlhdCI6MTc4MzU3NTM4MCwiZXhwIjoxNzg0MTgwMTgwfQ.smPBFh89tR2vb1PCU9aGhZHhyhKBqrab3bACUSL5lEw

# {
#     "googleBookId": "x8xtwgEACAAJ"
# }

# GET http://localhost:5000/api/books/library
# # PATCH http://localhost:5000/api/books/library/6a5079b1c2c29a775d6570bf
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNGM4MWJhMWY3MDYwYTJlZjcxZWVhMiIsImlhdCI6MTc4MzU3NTM4MCwiZXhwIjoxNzg0MTgwMTgwfQ.smPBFh89tR2vb1PCU9aGhZHhyhKBqrab3bACUSL5lEw

# {
#     "status": "Completed",
#     "currentPage": 120,
#     "rating": 5
# }

# POST  http://localhost:5000/api/notes
GET http://localhost:5000/api/notes?bookId = 6a5079b1c2c29a775d6570be
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNGM4MWJhMWY3MDYwYTJlZjcxZWVhMiIsImlhdCI6MTc4MzU3NTM4MCwiZXhwIjoxNzg0MTgwMTgwfQ.smPBFh89tR2vb1PCU9aGhZHhyhKBqrab3bACUSL5lEw

# {
#   "userBookId": "6a5079b1c2c29a775d6570bf",
#   "title": "Personal Legend",
#   "content": "When you want something, all the universe conspires in helping you to achieve it.",
#   "page": 24,
#   "chapter": "The Crystal Merchant",
#   "tags": ["personal-legend", "dreams", "destiny", "motivation"]
# }